### PR TITLE
PHP 7.2 images

### PR DESCRIPTION
**Pull request by kockodev**
Hey guys,

I'd like to add PHP 7.2 images with deprecated "mcrypt" and new "sodium" extension.

### CODE REVIEW

**Comment by geertw** [comment]
Many thanks for your contribution! :-)

**Comment by kockodev** [comment]
@geertw you are welcome :-) I hope it helps someone ...

**Comment by kockodev** [comment]
@geertw did you added tags here https://hub.docker.com/r/geertw/docker-php-ci/tags/ ? or is it automated?

**Comment by geertw** [comment]
I've added the tags and the images are currently building on Docker hub. It's indeed automated, so they are updated automatically when the source PHP image is updated (but Docker hub is a bit slow to build those images).

**Pull request merged**
